### ISSUE TITLE
Why do u use Rsocket

### ISSUE THREAD

**Issue by HelloTo4x** [making/tsunagu#8]
Hi,i am reading your code, why do you use Rsocket instead of other protocols like gRPC or socket, websocket... What is your use case which you use Rsocket, thank you so much

**Comment by making** [comment]
@HelloTo4x 

RSocket is a bidirectional protocol.
Server can be a requester to the client 
That means server can initiate a request to the client at any time out of the box. This is different from what grpc says "bidirectional".
This feature fits naturally what I want to achieve with tsunagu.

You can watch my talk abount RSocket at SpringOne last year.
https://tanzu.vmware.com/content/videos/learning-rsocket-using-rsc

Tsunagu actually uses WebSocket as a transport layer. WebSocket is too low level.
RSocket can use TCP instead of WebSocket. But I chose WebSocket because Spring allows the server to share ports with regular http (most requests coming to the tsunagu server) and rsocket apps. With TCP, you need to have different ports to http and rsocket. This can be a restriction when deploying to some environments like PaaS.
